select 
    QUERY_ID as QUERY_ID,
    START_TIME::DATE AS USAGE_DATE,
    WAREHOUSE_ID AS ENTITY_ID,
    WAREHOUSE_NAME AS ENTITY_NAME, 
    SUM(CREDITS_ATTRIBUTED_COMPUTE) AS CREDITS_USED_COMPUTE,
    SUM(CREDITS_ATTRIBUTED_COMPUTE) AS CREDITS_USED_CLOUD_SERVICES,
    SUM(CREDITS_ATTRIBUTED_COMPUTE) AS CREDITS_USED
from {{source('account_usage', 'query_attribution_history')}}
--FULL LOAD FOR FIRST RUN
{% if var('FIRST_LOAD') == false %}
WHERE START_TIME::DATE >= current_date - 2
{% endif %}

GROUP BY ALL