select 
    START_TIME::DATE AS USAGE_DATE,
    WAREHOUSE_ID AS ENTITY_ID,
    WAREHOUSE_NAME AS ENTITY_NAME, 
    SUM(CREDITS_USED_COMPUTE) AS CREDITS_USED_COMPUTE, 
    SUM(CREDITS_USED_CLOUD_SERVICES) AS CREDITS_USED_CLOUD_SERVICES, 
    SUM(CREDITS_USED) AS CREDITS_USED,
    SUM(CREDITS_ATTRIBUTED_COMPUTE_QUERIES) AS CREDITS_ATTRIBUTED_COMPUTE_QUERIES
from {{source('account_usage', 'warehouse_metering_history')}}
--FULL LOAD FOR FIRST RUN
{% if var('FIRST_LOAD') == false %}
WHERE START_TIME::DATE >= current_date - 2
{% endif %}

GROUP BY ALL