SBI_APAC_Snowflake_Cost_Monitoring:
  target: dev
  outputs:
    dev:
      type: snowflake
      role: '"SF_APA_SANDBOX-MONITORING"'
      warehouse: SANDBOX_MONITORING_WH
      database: MONITORING_DB
      schema: USAGE_MONITORING
      account: ' '
      user: ' '
    prd:
      type: snowflake
      role: '"SF_APA_SANDBOX-MONITORING"'
      warehouse: SANDBOX_MONITORING_WH
      database: MONITORING_DB
      schema: USAGE_MONITORING
      account: ' '
      user: ' '