{{
    config(
        materialized='incremental',
        unique_key=['usage_date', 'warehouse_id'],
        tags=["daily"]
    )
}}

WITH attributed_queries AS (

SELECT 
    QUERY_ID,
    USAGE_DATE,
    'WAREHOUSE_METERING' SERVICE_TYPE,
    'ATTRIBUTED_QUERIES' CATEGORY,
    ENTITY_ID,
    ENTITY_NAME, 
    CREDITS_USED_COMPUTE,
    CREDITS_USED_CLOUD_SERVICES,
    CREDITS_USED
FROM {{ref('query_attribution_history')}}
GROUP BY ALL

)

, warehouse_metering AS (

SELECT 
    null as QUERY_ID,
    USAGE_DATE,
    'WAREHOUSE_METERING' AS SERVICE_TYPE,
    'WAREHOUSE_METERING' AS CATEGORY,
    ENTITY_ID,
    ENTITY_NAME, 
    CREDITS_USED_COMPUTE, 
    CREDITS_USED_CLOUD_SERVICES, 
    CREDITS_USED
FROM {{ref('warehouse_metering_history')}}
GROUP BY ALL

)

, other_services AS (

SELECT 
    null as QUERY_ID,
    START_TIME::DATE as USAGE_DATE,
    SERVICE_TYPE,
    SERVICE_TYPE AS CATEGORY,
    ENTITY_ID,
    NAME AS ENTITY_NAME, 
    SUM(CREDITS_USED_COMPUTE) AS CREDITS_USED_COMPUTE, 
    SUM(CREDITS_USED_CLOUD_SERVICES) AS CREDITS_USED_CLOUD_SERVICES, 
    SUM(CREDITS_USED) AS CREDITS_USED
FROM SNOWFLAKE.ACCOUNT_USAGE.METERING_HISTORY
WHERE SERVICE_TYPE <> 'WAREHOUSE_METERING' 
GROUP BY ALL

)

, cloud_services_adjustment AS (

SELECT 
    null as QUERY_ID,
    USAGE_DATE,
    SERVICE_TYPE,
    'CLOUD_SERVICES_ADJUSTMENT' AS CATEGORY,
    -99 AS ENTITY_ID,
    'CLOUD_SERVICES_ADJUSTMENT' AS ENTITY_NAME, 
    0 AS CREDITS_USED_COMPUTE,
    SUM(CREDITS_ADJUSTMENT_CLOUD_SERVICES) AS CREDITS_USED_CLOUD_SERVICES,
    SUM(CREDITS_ADJUSTMENT_CLOUD_SERVICES) AS CREDITS_USED 
FROM SNOWFLAKE.ACCOUNT_USAGE.METERING_DAILY_HISTORY
WHERE CREDITS_ADJUSTMENT_CLOUD_SERVICES != 0 AND SERVICE_TYPE = 'WAREHOUSE_METERING' 
GROUP BY ALL

)

, attributed_queries_adjustment AS (


SELECT 
    null as QUERY_ID,
    wm.USAGE_DATE AS USAGE_DATE,
    wm.SERVICE_TYPE,
    'ATTRIBUTED_QUERIES_ADJUSTMENT' AS CATEGORY,
    wm.ENTITY_ID,
    wm.ENTITY_NAME, 
    SUM(wm.CREDITS_USED_COMPUTE) - SUM(qa.CREDITS_USED_COMPUTE) AS CREDITS_USED_COMPUTE,
    SUM(wm.CREDITS_USED_CLOUD_SERVICES) - SUM(qa.CREDITS_USED_CLOUD_SERVICES) AS CREDITS_USED_CLOUD_SERVICES,
    SUM(wm.CREDITS_USED) - SUM(qa.CREDITS_USED) AS CREDITS_USED 
FROM warehouse_metering wm
LEFT JOIN attributed_queries qa ON wm.USAGE_DATE = qa.USAGE_DATE AND wm.ENTITY_ID = qa.ENTITY_ID
GROUP BY ALL

)
, unattributed_queries AS (
SELECT 
    null as QUERY_ID,
    USAGE_DATE,
    'WAREHOUSE_METERING' AS SERVICE_TYPE,
    'UNATTRIBUTED_QUERIES' AS CATEGORY,
    ENTITY_ID,
    ENTITY_NAME, 
    CREDITS_USED_COMPUTE, 
    CREDITS_USED_CLOUD_SERVICES, 
    CREDITS_USED - CREDITS_ATTRIBUTED_COMPUTE_QUERIES AS CREDITS_USED
FROM {{ref('warehouse_metering_history')}}
)
SELECT * FROM attributed_queries
UNION ALL
SELECT * FROM unattributed_queries
UNION ALL
SELECT * FROM attributed_queries_adjustment
UNION ALL
SELECT * FROM other_services
UNION ALL
SELECT * FROM cloud_services_adjustment

 